project:
  type: website
  execute-dir: project
  # output-dir: _site

website:
  title: "2. Linear Algebra"          # ← 변경
  description: "강의 설명"           # ← 변경
  favicon: images/logo.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/kkonoo/2_linear_algebra  # ← 변경

  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Part 1. 기초"
        contents:
          - chapters/01_intro.qmd
          - chapters/02_r_basics.qmd
      # - section: "1. R env"
      #   contents: "part1/*.qmd"
      # - section: "2. Genomics"
      #   contents: "part2/*.qmd"
      # - section: "3. Omics"
      #   contents: "part3/*.qmd"
      # - section: "4. Multi-Omics"
      #   contents: "part4/*.qmd"
      # - section: "5. Capstone"
      #   contents: "part5/*.qmd"

  page-footer:
    left: "Copyright 2026, Eunji"


format:
  html:
    theme:
      light: cosmo
    css: assets/html.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    toc-float: true
    page-layout: full

    code-fold: false  
    code-copy: true
    highlight-style: github 

    number-sections: false
    smooth-scroll: true

    # grid:                       
    #   sidebar-width: 400px
    #   body-width: 1000px
    #   margin-width: 300px # toc

    # AI 채팅 위젯 전역 설정
    include-after-body: assets/ai-chat-init.html

  revealjs:
    css: assets/revealjs.css    # 슬라이드용


execute:
  freeze: auto          # 코드 실행 결과 캐시 (빠른 빌드)
  echo: true
  eval: false
  warning: false
  message: false

